"""
CortiX Module 5 — Ransomware Honeypot File Watcher

Uses Watchdog/inotify to monitor specific high-risk system paths 
for file renames, encryption events, and metadata alterations in real-time.
"""

import os
import logging
import time
from collections import defaultdict
from typing import Callable, Optional

try:
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
except ImportError:
    Observer = None
    FileSystemEventHandler = object

from cortix.config import config

logger = logging.getLogger("cortix.honeypot.watcher")


class HoneypotFileSystemHandler(FileSystemEventHandler):
    """
    Handles filesystem events generated by watchdog. 
    Aggregates events by PID/Process name to identify bulk encryption or renames.
    """

    def __init__(self, callback: Callable[[str, dict], None]):
        super().__init__()
        self.callback = callback
        # Store activity stats: key=pid (or dummy 'global'), value=dict of counts
        self.activity = defaultdict(lambda: {
            "renames": 0,
            "modified": 0,
            "created": 0,
            "last_time": time.time(),
        })

    def on_moved(self, event):
        """Called when a file or a directory is renamed or moved."""
        if event.is_directory:
            return

        dest_path = event.dest_path
        _, ext = os.path.splitext(dest_path)
        
        # Check for typical ransomware extensions
        ransomware_exts = [".locked", ".enc", ".crypted", ".crypto", ".pay", ".adolf", ".coop"]
        is_suspicious_ext = ext.lower() in ransomware_exts

        logger.debug("File moved/renamed: %s -> %s", event.src_path, dest_path)
        
        self.activity["global"]["renames"] += 1
        self.activity["global"]["last_time"] = time.time()

        # Emit alert immediately if target extension matches
        if is_suspicious_ext:
            self.callback(
                "suspicious_rename",
                {
                    "src_path": event.src_path,
                    "dest_path": dest_path,
                    "ext": ext,
                    "timestamp": time.time(),
                },
            )

    def on_modified(self, event):
        """Called when a file or directory is modified."""
        if event.is_directory:
            return

        logger.debug("File modified: %s", event.src_path)
        self.activity["global"]["modified"] += 1
        self.activity["global"]["last_time"] = time.time()

    def on_created(self, event):
        """Called when a file or directory is created."""
        if event.is_directory:
            return

        logger.debug("File created: %s", event.src_path)
        self.activity["global"]["created"] += 1
        self.activity["global"]["last_time"] = time.time()


class HoneypotWatcher:
    """
    Monitors folders using Watchdog Observers.
    Triggers behavior logs or traps upon threshold breaches.
    """

    def __init__(self, watch_dirs: list[str] = None):
        self.watch_dirs = watch_dirs or config.HONEYPOT_WATCH_DIRS
        self.observer = None
        self.handler = None
        self._callbacks: list[Callable] = []

    def register_callback(self, callback: Callable):
        self._callbacks.append(callback)

    def start(self):
        """Start file watching threads."""
        if Observer is None:
            logger.warning("Watchdog not installed. Honeypot file watcher cannot start.")
            return

        self.handler = HoneypotFileSystemHandler(self._dispatch_event)
        self.observer = Observer()

        started_dirs = []
        for path in self.watch_dirs:
            if os.path.exists(path):
                self.observer.schedule(self.handler, path, recursive=True)
                started_dirs.append(path)
            else:
                logger.debug("Watch directory %s does not exist. Skipping.", path)

        if started_dirs:
            self.observer.start()
            logger.info("Ransomware honeypot watcher active on paths: %s", started_dirs)
        else:
            logger.warning("No valid directory paths available to monitor.")

    def stop(self):
        """Stop file watching threads."""
        if self.observer:
            self.observer.stop()
            self.observer.join()
            self.observer = None
            logger.info("Ransomware honeypot watcher stopped.")

    def _dispatch_event(self, event_type: str, data: dict):
        for cb in self._callbacks:
            try:
                cb(event_type, data)
            except Exception as exc:
                logger.error("Honeypot watcher callback error: %s", exc)

    def get_stats(self) -> dict:
        """Return rolling file events statistics."""
        if self.handler:
            glob = self.handler.activity["global"]
            return {
                "renames_count": glob["renames"],
                "modified_count": glob["modified"],
                "created_count": glob["created"],
                "last_active": glob["last_time"],
            }
        return {"renames_count": 0, "modified_count": 0, "created_count": 0, "last_active": 0.0}
